### ISSUE TITLE
[roadmap] MobTalker for Minetest objectives

### ISSUE THREAD

**Issue by Rui914** [Rui914/mobtalker#7]
# Objectives #
- [ ] Add other mobs
- [ ] Add conversation
- [ ] Save and Load
- [ ] The execution of the script file
